public class Day7
{
    static final String testInput = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """;

    static String input = """
            """;

    public static void main(String[] args)
    {
        Day7 event = new Day7();
        event.solvePart1();
        //event.solvePart2();
    }

    private void solvePart1()
    {

    }

    private void solvePart2()
    {
    }
}
